
##
# RLStevenson Theme Options
####

# For baseurl:
# Use '' for / or '/your-dir' for another directory

title:		tngtied's gitblog
description:	'tngtied의 깃블로그입니다'
freetext:	'능동적으로 학습하는 신입 백엔드 개발자 최건혜입니다. 모르는 문제를 마주쳤을 때 적극적으로 관련된 것들을
찾아보고, 물어보고, 학습합니다. 새로운 툴, 즉 새로운 플랫폼, 환경 그리고 프레임워크가 주어졌을 때 빠르게 적응합니다.
주어진 목표대로 어플리케이션의 로직을 짜내고 실제로 기능하게 만드는 것으로부터 큰 재미를 느낍니다.
'
baseurl:	'/'
paginate:	3
version:	0.1.1
colorscheme:	scheme-gulfracing
permalink: /:categories/:title

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

author:
 name:		'tngtied'

# defaults:
#   -
#     scope:
#       path: "/post/"
#       type: "pages"
      

gems:		[jekyll-paginate]

exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem']
